[build]
  publish = "public"

[build.processing]
  skip_processing = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Robots-Tag = "noindex, nofollow"
