from pathlib import Path
import json,html
R=Path(__file__).resolve().parents[1];O=R/'public/english/round2';D=R/'docs/english-round2'
css=(R/'public/assets/style.css').read_text()+'''\ntextarea{display:block;width:100%;padding:11px 12px;margin-top:8px;border:1px solid #cfd5df;border-radius:9px;font:inherit;resize:vertical}a{color:#3a4db2}details{margin:12px 0}summary{cursor:pointer;font-weight:650;line-height:1.7}table{width:100%;border-collapse:collapse;font-size:14px}td,th{padding:9px;text-align:left;border-bottom:1px solid #e5e7eb;vertical-align:top}p,li{line-height:1.75}.q,.wrong-item{overflow-wrap:anywhere}.feedback{line-height:1.8}.table-wrap{overflow-x:auto}.status-note{background:#fff9e8;padding:12px;border-radius:9px}.section-links{display:flex;flex-wrap:wrap;gap:10px}button:focus-visible,a:focus-visible,input:focus-visible,textarea:focus-visible{outline:3px solid #5367d9;outline-offset:2px}@media(max-width:680px){.toolbar{top:0}.hero{padding:18px}td,th{padding:7px}.table-wrap table{min-width:470px}}'''
engine=(O/'engine.js').read_text();data=json.loads((D/'first-batch-questions.json').read_text());audit=json.loads((D/'round1-audit.json').read_text());plan=json.loads((D/'plan.json').read_text())
E=html.escape
def shell(title,body,script=''):
 return '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+E(title)+'</title><style>'+css+'</style></head><body><main class="wrap">'+body+'</main>'+script+'<script>if(location.protocol!=="file:"){const s=document.createElement("script");s.src="/shared/nav.js";document.body.append(s);}</script></body></html>'
for day,c in data.items():
 body=f'''<div class="hero"><p class="small">清许英语 · 第二轮 5000词复习</p><h1>清许高考词汇 Day {day}</h1><div class="sub">范围：<b>{E(c['range'])}</b><br>建议用时：30–40分钟 · 沿用第一轮形式</div><div class="meta"><div class="metric">题量<b>70题</b></div><div class="metric">正式总分<b>100分</b></div><div class="metric">滚动复测<b>10分*</b></div><div class="metric">保存方式<b>自动记录</b></div></div><div class="review-note">* 复测独立计分。先完成全部首答再提交；翻译按首答自评。查词、不确定和订正分别记录。首批复测依据已找回的跨阶段反馈编写，后续按实际结果调整。</div></div>
<div id="startPanel" class="card start-panel"><h2>开始前</h2><p>如这几页有从未学过的词，可先完成补学，再关书测试。遇到不会的文字题可填写“不会”，并标记不确定。</p><p class="sub">在线登录后可自动保存作答；离线版请下载结果反馈。刷新可恢复，重新打开或切出页面后需点“继续”。</p><input id="studentName" type="text" aria-label="学生姓名" value="清许"><div><button id="startBtn" class="primary">开始测试</button></div></div>
<p id="saveNotice" class="small" role="status"></p><div id="exam" class="hidden"><div class="toolbar"><div class="toolbar-inner"><div><span id="answeredPill" class="pill">已答 0/70</span><span id="lookupPill" class="pill">查词 0 次</span><div class="progress"><div id="progressBar"></div></div></div><div class="toolbar-actions"><button id="lookupBtn">记录查词</button><button id="pauseBtn">暂停</button><button id="submitObjectiveBtn" class="primary">提交全部首答</button></div><div id="timer" class="timer">00:00:00</div></div></div><div id="questions"></div><div id="manualFinalize" class="card hidden"><h2>翻译自评</h2><p>客观题及翻译首答均已锁定。按每题列出的两个要点评分：各要点1分，共2分；合理同义表达和英美拼写均可。返回各翻译题勾选分数，再生成结果。</p><button id="finalizeBtn" class="primary">生成最终结果</button></div></div>
<div id="result" class="card result"><h2>Day {day} 测试结果</h2><div class="result-grid"><div>正式总分<div class="big" id="totalScore">--</div></div><div>滚动复测<div class="big" id="reviewScore">--</div></div><div>用时<div class="big" id="timeUsed">--</div></div><div>错题数<div class="big" id="wrongCount">--</div></div></div><p class="band" id="resultBand"></p><h3>分类表现</h3><div id="categoryScores"></div><h3>错题与不稳定题</h3><div id="wrongList"></div><div class="footer-actions"><button id="copyBtn">复制总结</button><button id="downloadBtn">下载结果 TXT</button><button id="downloadJsonBtn">下载完整记录 JSON</button><button id="restartBtn">归档并重做</button></div><textarea id="copyFallback" class="hidden" aria-label="可复制的结果总结" rows="12" readonly></textarea></div>
<nav class="navbar"><a class="btnlink" href="index.html">返回第二轮总览</a>{f'<a class="btnlink" href="day{int(day)+1}.html">Day {int(day)+1} →</a>' if int(day)<34 else '<span class="small">Day35起：按本批结果继续出题</span>'}</nav><p class="small">来源：新手册印刷页{c['pages'][0]}–{c['pages'][1]}（PDF页码加1）及已找回的第一轮反馈。题目为原创变式；计分不是逐词覆盖率。</p>'''
 script='<script>window.ROUND2_CONFIG='+json.dumps(c,ensure_ascii=False).replace('</','<\\/')+';</script><script>'+engine+'</script>'
 (O/f'day{day}.html').write_text(shell(f'清许第二轮 Day {day}',body,script))
statuses={}
for e in audit['events']:statuses[e['status']]=statuses.get(e['status'],0)+1
body='''<div class="hero"><p class="small">清许英语 · 第一轮完成后</p><h1>第二轮词汇复习</h1><p class="sub">5000词手册 × Day1–31历史反馈<br>40次训练 · 每次70题 · 100分主卷＋10分滚动复测</p><div class="meta"><div class="metric">已出题<b>3套 / 210题</b></div><div class="metric">计划总数<b>40次</b></div><div class="metric">词表范围<b>92页</b></div><div class="metric">每天建议<b>30–40分钟</b></div></div></div>
<section class="card"><h2>先从这里开始</h2><p>按 Day32 → Day33 → Day34 依次完成；在线登录后自动保存；离线使用可下载结果。滚动题含早期、中期、近期项目，后续依据实际反馈调整。切出答题页会自动暂停。</p>'''
for d,c in data.items():body+=f'<div class="day-card"><div><span class="tag">第二轮 · 第{int(d)-31}次</span><h2>Day {d}</h2><div class="sub">{E(c["range"])}</div></div><a class="btnlink primary" href="day{d}.html">开始作答</a></div>'
body+='''</section><section class="card"><h2>第一轮记录核对</h2><p class="status-note">已找回24天报告信息，其中Day4、Day9仍需原报告补核。Day10、Day11–15、Day23共7天未找到实测报告。这里标记的是资料缺口，不代表清许没有完成。</p><p>所有已找回的历史标错项目都已进入台账，并区分有效复测、合理答案、题目歧义、疑似输入失误和判分故障。原始成绩保留。</p><a class="btnlink" href="audit.html">查看31天覆盖表与核验台账</a></section><section class="card"><h2>40次复习安排</h2><p>词表页码使用书上印刷页码，PDF页码加1。每9次词段训练后做1次累积验收。尚未出题的部分只表示计划，不能标记为完成。</p><div class="table-wrap"><table><thead><tr><th>训练</th><th>印刷页</th><th>内容</th><th>状态</th></tr></thead><tbody>'''
for s in plan['sessions']:body+=f'<tr><td>Day {s["day"]}</td><td>{s["pages"][0]}–{s["pages"][1]}</td><td>{s["type"]}</td><td>{s["state"]}</td></tr>'
body+='''</tbody></table></div></section><section class="card"><h2>怎样算复习稳了</h2><p>完成订正后，约2天与7天再换语境检查；两次独立答对才退出高频复测。尚未学过、学过遗忘、拼写失误、题目歧义分别处理。训练编号不等于自然日，遇到校内任务可顺延。</p><p class="small">在线版登录后可保存到账号，换设备恢复；离线版记录保存在当前设备浏览器。TXT和JSON仍可作为备份。旧设备历史记录需在原页面确认导入后才能同步。</p></section>'''
(O/'index.html').write_text(shell('清许英语第二轮总览',body))
body=f'''<div class="hero"><p class="small">家长与复盘记录</p><h1>Day1–31记录覆盖与错题核验</h1><p>共找回 {len(audit['events'])} 条历史标错记录，包含10条Day2判分故障。这个数量不是有效错题数，也不是31天完整错题总数。</p><p class="sub">来源：本会话原报告、历史对话检索及仓库原题。历史摘要不等于原始报告全文。历史分数不因本次核验自动改写。</p></div><a class="btnlink" href="index.html">返回第二轮</a><section class="card"><h2>覆盖情况</h2><p class="status-note">缺失：Day10、Day11–15、Day23。Day4、Day9仅有历史转述；Day1第9题首答存在摘要冲突。补充时请提供原报告TXT/复制总结，或完整JSON。</p><div class="table-wrap"><table><tr><th>Day</th><th>报告状态</th><th>原主卷分</th><th>标错记录</th></tr>'''
for c in audit['coverage']:body+=f'<tr><td>{c["day"]}</td><td>{c["status"]}</td><td>{str(c["reported_score"])+"/100" if c["reported_score"] is not None else "—"}</td><td>{c["event_count"] if c["reported_score"] is not None else "未知"}</td></tr>'
body+='</table></div></section><section class="card"><h2>核验分类</h2><p>'+ '；'.join(f'{k} {v}条' for k,v in statuses.items())+'</p><p>“待复测”表示纳入后续独立检查，并不等于已核验全部历史评分。待核验项目仅作诊断，不预设学生不会。</p></section>'
for day in range(1,32):
 es=[e for e in audit['events'] if e['day']==day]
 if not es:continue
 body+=f'<details class="card"><summary>Day {day} · {len(es)}条历史标错记录</summary>'
 for e in es:
  body+=f'<div class="wrong-item"><b>第{e["no"]}题 · {E(e["status"])}</b><p>{E(e["question"] or "原题定位待补")}</p><p>原首答：{E(e["user"])}<br>原报告参考：{E(e["reported_answer"])}</p><p>{E(e["audit_note"])}</p><p class="small">证据：{E(e["evidence"])}<br>第二轮：{E(e["second_round_action"])}'+(f'；首次安排 Day{e["planned_first_review"]}' if e.get('planned_first_review') else '')+'</p></div>'
 body+='</details>'
(O/'audit.html').write_text(shell('清许第一轮31天错题核验台账',body))
portal=R/'public/english/index.html';s=portal.read_text();needle='<div class="list">';new='<div class="row"><div><h2>第二轮 · 5000词复习</h2><p>40次计划；首批Day32–34已出题，含31天历史反馈核验台账。</p></div><a href="round2/">打开第二轮</a></div>'
if 'href="round2/"' not in s:s=s.replace(needle,needle+new);portal.write_text(s)
print('Rendered 3 standalone tests, index, and audit page')
